### ISSUE TITLE
Long-term vision

### ISSUE THREAD

**Issue by YoranBrondsema** [bustlelabs/content-kit-editor#137]
Hi,

We're HSTRY, an education technology start-up. Up until now, we have been using our own `contenteditable` rich-text editor but are now running into its limitations. I don't think it's necessary for me to repeat how much of a PITA it is to make `contenteditable` run consistently across all browsers. As an FYI, our front-end is built with Ember.js.

Until now, only admins in the HSTRY application had rich-text editing capabilities. However, we now want to open it up to all our users. We want to step away from our direct-to-HTML `contenteditable` editor because it's inconsistent across browsers and not easily extendible with custom "tags" (what you call "cards"). But since 50k+ users will now start adding rich-text information to their content, we want to go for a solution that will work long-term. It will be extremely difficult for us to change the underlying representation once we've pushed one live.

We have been looking into alternatives and it looks like `content-kit-editor` is the best solution for us. It is open-source, actively developed, and I like that it's been designed so that it's easily extendible with custom "cards". The Mobiledoc format looks clean and well-thought out.

My question now is: what is the long-term vision of the project? I understand that there's a company behind it, Bustle.

* Is it going to remain open-source?
* Will it be maintained, I would assume by people from Bustle (at least initially)?

Naturally, if HSTRY chooses to integrate `content-kit-editor`, we will commit ourselves to push any improvements that we make back upstream.

I'm sorry for the fact that this is not a proper "issue" but it seemed to me like the best place to ask this question.

Thank you,

Yoran

**Comment by mixonic** [comment]
> Is it going to remain open-source?

Of course. Like any MIT licensed software someone could make an internal fork (or public fork) but I don't see any reason to think that will happen. If they do, it just means the internal code diverges.

> Will it be maintained, I would assume by people from Bustle (at least initially)?

Bustle has been excited about this since long before 201 Created started working on it :-) They are using it internally and will continue to expands its use. Their public track record supporting OSS is pretty great, and that coupled with my own vote of confidence in their great team should be a positive signal.

Cory and I would like to continue improving Content-Kit's community and technology as long as we can. Several other companies are looking at the same commitment to Content-Kit that HSTRY is considering, and have already expressed an interest in contributing via a number of avenues. Cory and I have a pretty good track record of stable OSS projects ourselves, and we hope to foster a healthy community here that ensures the project's longevity. Too many of these libs flame out because contribution is overly difficult.

Lastly, from a pragmatic standpoint I encourage you to look at and use the APIs we have available today and evaluate them. We're planning to release an Ember addon that makes building custom UIs a snap, but there are plans and there is code on the table today. Always happy to chat if you want to discuss things further- you can usually find me or Cory in the [gitter chat](https://gitter.im/bustlelabs/content-kit-editor).
