### ISSUE TITLE
Toolbar support?

### ISSUE THREAD

**Issue by vitosamson** [bustlelabs/content-kit-editor#206]
I see in the demo that there's a very simple toolbar example, but can't find any docs on it.

Does the editor have a builtin toolbar? If not, how would one go about building an external one?

@mixonic mentioned in https://github.com/bustlelabs/content-kit-editor/issues/121 that "I believe the toolbar buttons should be going away entirely, and be supplanted by ember components in an addon." - does this mean this editor is moving towards an Ember-only component?

**Comment by mixonic** [comment]
@vitosamson We're also in the gitter chat (linked on the readme) for general questions.

https://github.com/bustlelabs/ember-content-kit is where the UI for the demo lives.

> Does the editor have a builtin toolbar?

Our conversations have led to the recognition that there is little desire for a stock UX. Pretty much everyone has a custom UI they want. To that end, we've instead focused on a creating programmatic APIs for content-kit that allow for any UI/UX to be created.

> If not, how would one go about building an external one?

The readme is currently our major source of documentation. It should tell you how to use the programmatic APIs and do things like toggle bold/italic. The ember-content-kit project is probably also useful as a reference implementation with Ember.

> does this mean this editor is moving towards an Ember-only component?

A thousand times no. The editor is becoming more programmatic and thus even more generic than it was when it provided a UI. It turns out frontend frameworks like React and Ember are better for customizing and creating UI than any plugin API we could cobble together. Creating the Ember addon has allowed us to dogfood those APIs and be sure that custom experiences can be created regardless of framework.

We are totally committed to being a good foundation for an editor built with any additional toolset.

Let me know if you have additional questions, closing this for now though!

**Comment by bantic** [comment]
@vitosamson The ember-addon [uses the `cursorDidChange` hook](https://github.com/bustlelabs/ember-content-kit/blob/2e019600242fbbd93c01c76a16f152248499ff06/addon/components/content-kit-editor/component.js#L193-L210) to detect when to update its toolbar buttons' `"active"` state, and uses the [editor's `postEditor` API](https://github.com/bustlelabs/ember-content-kit/blob/2e019600242fbbd93c01c76a16f152248499ff06/addon/components/content-kit-editor/component.js#L59-L103) for wiring up the buttons. Hopefully that gives some more context on how a toolbar would be built by a different framework. Please let us know any additional questions you have, here or in gitter, so that we can continue to make the API expressive enough. Reference toolbar implementations in other frameworks would be great to see! :)

**Comment by vitosamson** [comment]
Awesome, thanks for the replies. Going to play around with this. I'll hop onto gitter if I've got any more questions.
